public class Tweet{
		
	String content;
	String author;

	public Tweet(String c, String a){
		content = c;
		author = a;
	}


	public String getContent(){
		return content;}
	public String getAuthor(){
		return author;}

	public String getTweet(){ //returns both author and content
		return getAuthor() + ": " + getContent();
	}


	public static void main(String[] args){
		Tweet mperson = new Tweet("It is now possible to learn about a person’s mobility preferences from data generated by his or her smartphone." , "mperson");
		Tweet j1 = new Tweet("Hello World!", "Jerbened");
		Tweet k1 = new Tweet("What is a java?", "Kyle");
		Tweet s1 = new Tweet("I'm going on vacation for a long time and my home will be all empty, I hope no one breaks in!", "Steve McSmarty");

		System.out.println(j1.getTweet());
		System.out.println(k1.getTweet());
		System.out.println(s1.getTweet());
		System.out.println(mperson.getTweet());

	}


}
			
